name: Build and Release Binary

on:
  create:

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            provisioner-x86_64-unknown-linux-gnu
